services:
  notebook:
    image: gelos:latest
    build: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
       - .:/app/ 
       - ${RAW_PATH}:/app/data/raw/
       - ${PROCESSED_PATH}:/app/data/processed/
       - ${EXTERNAL_PATH}:/app/data/external/
    command: jupyter lab --ip=0.0.0.0 --allow-root
    ports:
       - "${HOST_PORT}:8888"
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  test:
    image: gelos-test:latest
    build: 
      context: .
      target: test
    volumes:
      - .:/app/
    command: make test